trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

workspace:
  clean: all
steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
              workingDir: ./heroes-frontend
            displayName: "Npm Install"

          - task: Npm@1
            inputs:
              command: custom
              workingDir: ./heroes-frontend
              customCommand: "run build"
            displayName: "Build Angular app"
          
          # - task: Npm@1
          #   inputs:
          #     command: custom
          #     workingDir: ./heroes-frontend/src
          #     customCommand: "run test"
          #   displayName: "Test Angular app"
          
          - script: |
              mkdir $(Build.ArtifactStagingDirectory)/dist
              cp -rf dist/heroes-frontend/* $(Build.ArtifactStagingDirectory)/dist
            displayName: Copy dist contents

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"
         
         
         