trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

workspace:
  clean: all
steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"
          
          # - script: |
          #     find .
          #     npm install -g @angular/cli
          #     npm install

          - task: Npm@1
            inputs:
              command: "install"
              workingDir: ./heroes-frontend
            displayName: "Npm Install"

          - task: Npm@1
            inputs:
              command: custom
              
              customCommand: "run build"
            displayName: "Build Angular app"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run test"
            displayName: "Test Angular app"
         
         
         